using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace ProjectAliCanSariboga
{
    public partial class FormRaporEkrani : Form
    {

        SqlConnection SqlConn = new SqlConnection("SQL connection here");
        public FormRaporEkrani()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void FormRaporEkrani_Load(object sender, EventArgs e)
        {
            
        }

        private void repositoryItemButtonEdit1_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Islem Tamamlanmistir.");
        }
    }
}
